version: "3"

services:
  sc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISPLAY: 192.168.1.6:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/samples
